### PR TITLE
fix flaky PerformanceTest  

### PR DESCRIPTION
**Pull request by wycccccc**
#195 該bug的產生原因為adminClient可能會存在還沒有來得及創建topic,之後的程序就需要抓topic了，所以這裡給它一個等待的時間。

### CODE REVIEW

**Review by chia7712 — COMMENTED** [review]
Could you use “until” function to make sure the state gets stable?

**Comment by wycccccc** [comment]
ok 它跑了100多遍沒有報錯，我想它現在正常了。
Screenshot from 2022-01-23 16-56-16

**Comment by chia7712** [comment]
@wycccccc please take a look at comment

https://github.com/skiptests/astraea/pull/196#pullrequestreview-860230082

**Comment by wycccccc** [comment]
OK,I think it should be right now.

**Review by chia7712 — APPROVED** [review]
+1

**Pull request merged**
